"""fix_docs_table_schema

Revision ID: 04f751ef1854
Revises: dd6851322c09
Create Date: 2026-01-18 12:16:42.193431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f751ef1854'
down_revision: Union[str, Sequence[str], None] = 'dd6851322c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.add_column('docs', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('docs', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('docs', sa.Column('document_uuids', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_docs_docs_id'), table_name='docs')
    op.drop_index(op.f('ix_docs_document_uuid'), table_name='docs')
    op.create_index(op.f('ix_docs_id'), 'docs', ['id'], unique=False)
    op.drop_column('docs', 'document_uuid')
    op.drop_column('docs', 'docs_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('docs_id', sa.INTEGER(), nullable=False))
    op.add_column('docs', sa.Column('document_uuid', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_docs_id'), table_name='docs')
    op.create_index(op.f('ix_docs_document_uuid'), 'docs', ['document_uuid'], unique=False)
    op.create_index(op.f('ix_docs_docs_id'), 'docs', ['docs_id'], unique=False)
    op.drop_column('docs', 'document_uuids')
    op.drop_column('docs', 'title')
    op.drop_column('docs', 'id')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
